## docker-compose.yml
## https://docs.docker.com/compose/compose-file/compose-file-v2/
---
version: "2"

services:
  tor-proxy:
    build: .
    environment:
      TOR_MAX_CIRCUIT_DIRTNESS: 600
      TOR_PORT_BASE: 5050
      TOR_PORT_AMOUNT: 10
