# docker-compose.yml
# https://docs.docker.com/compose/compose-file/compose-file-v2/
# https://docs.docker.com/compose/compose-file/compose-file-v3/

---

version: "3.3"

services:
  tor-proxy:
    build: .
    restart: "no"
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:8404:8404"
    environment:
      TOR_MAX_CIRCUIT_DIRTNESS: 600
      TOR_PORT_BASE: 9060
      TOR_PORT_AMOUNT: 20
      TOR_EXPOSE_PORT: 1
