## .github/workflows/build-image.yml
## https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
---

name: docker-image

on: [ push, pull_request ]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: "docker.pkg.github.com"
      # CONTAINER_IMAGE: "docker.pkg.github.com/${{ github.repository }}/image"
      CONTAINER_IMAGE: "${{ secrets.DOCKERHUB_USERNAME }}/tor-proxy"

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build --tag="${{ github.sha }}" .
          docker image tag ${{ github.sha }} "${CONTAINER_IMAGE}:${GITHUB_REF##*/}"
          docker push "${CONTAINER_IMAGE}:${GITHUB_REF##*/}"
          docker image tag ${{ github.sha }} "${CONTAINER_IMAGE}:latest"
          docker push "${CONTAINER_IMAGE}:latest"

      - name: Mark image stable
        if: github.ref == 'refs/heads/master'
        run: |
          docker image tag ${{ github.sha }} "${CONTAINER_IMAGE}:stable"
          docker push "${CONTAINER_IMAGE}:stable"
