## .github/workflows/build-image.yml
## https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
---

name: docker-image

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-image.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - 'entrypoint.sh'

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            workutils/tor-proxy
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
