## .github/workflows/shellcheck.yml
## https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
---

name: shellcheck

on:
  push:
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**.sh'

jobs:
  shellcheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install -y shellcheck

      - name: Shellcheck
        run: |
          shellcheck *.sh
